server:
  port: 4000
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_hub
    username: root
    password: "CcmN*`6@3T9H%P#yg^V<7v"
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    open-in-view: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

custom:
  authorization:
    authorities:
      - manage-users
      - manage-projects
    roles:
      - ADMIN
      - MANAGER
      - USER
    authType: 1
  password:
    encoders:
      - scrypt
      - bcrypt
      - argon2
      - pbkdf2
    idless: scrypt
  recaptcha:
    secret: "6LcyyEMpAAAAANm0qZB6kzDQRT5Li4FSGCTe8ESf"
