registration-port: 4000

users-db-url: jdbc:mysql://localhost:3306/identity_hub
users-db-user: root
users-db-password: "CcmN*`6@3T9H%P#yg^V<7v"

authorities: manage-users,manage-projects
password-encoders: scrypt,bcrypt,argon2,pbkdf2
password-idless: scrypt

recaptcha-secret: "6LcyyEMpAAAAANm0qZB6kzDQRT5Li4FSGCTe8ESf"
allowed-cors-uri: http://localhost:4001,http://127.0.0.1:4001,http://localhost:7080,http://127.0.0.1:7080

server:
  port: ${registration-port}
  error:
    include-message: always

spring:
  datasource:
    url: ${registration.users-db-url:${users-db-url}}
    username: ${registration.users-db-user:${users-db-user}}
    password: ${registration.users-db-password:${users-db-password}}
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    open-in-view: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  config:
    import: optional:file:./configuration.yml

custom:
  authorization:
    authorities: ${registration.authorities:${authorities}}
    roles:
      - ADMIN
      - MANAGER
      - USER
    authType: 1
  password:
    encoders: ${registration.password-encoders:${password-encoders}}
    idless: ${registration.password-idless:${password-idless}}
  recaptcha:
    secret: ${registration.recaptcha-secret:${recaptcha-secret}}
  allowed-cors-uri: ${registration.allowed-cors-uri:${allowed-cors-uri}}

